### ISSUE TITLE
[Windows] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by mingzhou** [jasperam/playground#3]
![image](https://user-images.githubusercontent.com/1262067/41080479-4850f9ba-6a59-11e8-9f20-c2487202baa8.png)

**Comment by mingzhou** [comment]
内存不够会报这个错误。释放了内存，重启程序就正常了。

https://github.com/tensorflow/tensorflow/issues/7072

**Comment by Questdream** [comment]
> 内存不够会报这个错误。释放了内存，重启程序就正常了。
> 
> [tensorflow/tensorflow#7072](https://github.com/tensorflow/tensorflow/issues/7072)

你好，这个你是怎么释放内存的呀，我也是这个问题failed to create cublas handle: CUBLAS_STATUS_INTERNAL_ERROR
